### ISSUE TITLE
Please clarify how this is configured?

### ISSUE THREAD

**Issue by happyZxk** [strapi/LaunchPad#14]
## Fix
```js
Strapi (example in ./strapi/.env.example):

STRAPI_ADMIN_CLIENT_URL=<url-of-nextjs>

STRAPI_ADMIN_CLIENT_PREVIEW_SECRET=<a-random-token>

Create a ./strapi/.env file with these variables

Next.js (example in ./next/.env.sample):

NEXT_PUBLIC_API_URL=<url-of-strapi> (mandatory)

PREVIEW_SECRET=<the-same-random-token-as-for-strapi>

Create a ./next/.env file with these variables
```
[](url)
<img width="1756" alt="image" src="https://github.com/user-attachments/assets/20964e7c-6cf8-42bb-b284-049f0fd8ddd9">
<img width="1641" alt="image" src="https://github.com/user-attachments/assets/85c9e6ee-10c3-4b7b-b286-5d798cf4b15b">

**Comment by Mcastres** [comment]
Hello @happyZxk 👋 

It's simple, based on what you sent, this how it should look like:

`./strapi/.env`

```
STRAPI_ADMIN_CLIENT_URL=http://localhost:3000
STRAPI_ADMIN_CLIENT_PREVIEW_SECRET=43fsdfu2f912340j4314f32fn9f3
```


`./next/.env`

```
NEXT_PUBLIC_API_URL=http://localhost:1337
PREVIEW_SECRET=43fsdfu2f912340j4314f32fn9f3
```

**Comment by liaoyio** [comment]
Hello @Mcastres  👋  

After I pulled the code and followed the README document, Next.js ran into an error。

<img width="1282" alt="Image" src="https://github.com/user-attachments/assets/939cf43d-1e5a-4cec-8cbd-854af17e520f" />

When filling in PREVIEW_SECRET, I used API Tokens. Sorry, I'm not sure how to set it.
<img width="1325" alt="Image" src="https://github.com/user-attachments/assets/1cf100c7-a3ff-4f6a-80ad-53af6369d175" />


<img width="1555" alt="Image" src="https://github.com/user-attachments/assets/199a4d97-37eb-49d0-b97c-a80ae26e7565" />

How can I fix this error ?

The log is as follows:
```
FetchContentTypeError TypeError: fetch failed
    at node:internal/deps/undici/undici:12625:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchContentType (webpack-internal:///(rsc)/./lib/strapi/fetchContentType.ts:32:26)
    at async Module.generateMetadata (webpack-internal:///(rsc)/./app/[locale]/(marketing)/page.tsx:18:22) {
  cause: Error: connect ECONNREFUSED ::1:1337
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 1337
  }
}
 ⨯ app/[locale]/(marketing)/page.tsx (44:35) @ localizations
 ⨯ TypeError: Cannot read properties of undefined (reading 'localizations')
    at HomePage (page.tsx:36:37)
digest: "17653974"
  42 |   );
  43 |
> 44 |   const localizedSlugs = pageData.localizations?.reduce(
     |                                   ^
  45 |     (acc: Record<string, string>, localization: any) => {
  46 |       acc[localization.locale] = "";
  47 |       return acc;
 ⨯ app/[locale]/layout.tsx (59:48) @ navbar
 ⨯ TypeError: Cannot read properties of undefined (reading 'navbar')
    at LocaleLayout (./app/[locale]/layout.tsx:55:44)
digest: "4049467898"
  57 |                         )}
  58 |                     >
> 59 |                         <Navbar data={pageData.navbar} locale={locale} />
     |                                                ^
  60 |                         {children}
  61 |                         <Footer data={pageData.footer} locale={locale} />
  62 |                     </body>
 ⨯ app/[locale]/layout.tsx (59:48) @ navbar
 ⨯ TypeError: Cannot read properties of undefined (reading 'navbar')
    at LocaleLayout (./app/[locale]/layout.tsx:55:44)
digest: "4049467898"
  57 |                         )}
  58 |                     >
> 59 |                         <Navbar data={pageData.navbar} locale={locale} />
     |                                                ^
  60 |                         {children}
  61 |                         <Footer data={pageData.footer} locale={locale} />
  62 |                     </body>
FetchContentTypeError TypeError: fetch failed
```

**Comment by Mcastres** [comment]
Do you confirm that Strapi was running?

**Comment by liaoyio** [comment]
I'm sure my strapi is running, and when I use Postman to access http://localhost:1337/api/global, I can get data.

node：v18.20.7
yarn： 1.22.22
next.js: 14.2.3
strapi: 5.12.4


I tried to test it with the following code：
```
export default async function Home() {
  
  // ❌  fetch failed
  const data = await fetch(`http://localhost:1337/api/global`, {
    method: 'GET',
    cache: 'no-store',
  });

 // ✅  fetch success
 // const data = await fetch('https://jsonplaceholder.typicode.com/posts');

  const posts = await data.json()
  console.log('posts', posts)
  return (
    <div>{posts}</div>
  )
}

```

error:

```
 ⨯ TypeError: fetch failed
    at async Home (src/app/page.tsx:2:15)
  1 | export default async function Home() {
> 2 |   const data = await fetch(`http://localhost:1337/api/global`, {
    |               ^
  3 |     method: 'GET',
  4 |     cache: 'no-store',
  5 |   }); {
  digest: '2722656481',
  [cause]: Error: connect ECONNREFUSED ::1:1337
      at <unknown> (Error: connect ECONNREFUSED ::1:1337) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 1337
  }
}
 GET / 500 in 134ms
```
