### ISSUE TITLE
@strapi/email dependency seems to be missing in strapi/package.json

### ISSUE THREAD

**Issue by webhype** [strapi/LaunchPad#8]
### Describe your request

@strapi/email dependency seems to be missing in strapi/package.json

### Steps to reproduce the behavior

1. On a fresh installation, execute `yarn seed` from within strapi folder

```
$ yarn seed
yarn run v1.22.22
warning ../../package.json: No license field
$ strapi import -f ./data/export_20240925113338.tar.gz
? The import will delete your existing data! Are you sure you want to proceed? Yes
/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js:65
          throw new Error(`${declaration.resolve} couldn't be resolved`);
                ^

Error: @strapi/email/package.json couldn't be resolved
    at toDetailedDeclaration (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js:65:17)
    at Module.getEnabledPlugins (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js:83:10)
    at loadPlugins (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/core/dist/loaders/plugins/index.js:96:50)
    at Module.loadApplicationContext (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/core/dist/loaders/index.js:16:5)
    at Object.register (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/core/dist/providers/registries.js:26:17)
    at Strapi.register (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/core/dist/Strapi.js:322:32)
    at Strapi.load (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/core/dist/Strapi.js:314:16)
    at Module.createStrapiInstance (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/strapi/dist/cli/utils/data-transfer.js:116:22)
    at async Command.action (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/@strapi/strapi/dist/cli/commands/import/action.js:22:26)
    at async Command.parseAsync (/Users/macuser/dev/strapi-nextjs-launchpad/strapi/node_modules/commander/lib/command.js:923:5)

Node.js v18.20.4
error Command failed with exit code 1.

```
### Expected behavior

That it succeed in seeding the site.

**Comment by Mcastres** [comment]
I did create a fresh installation and didn't run through the issue :/

**Comment by StrapiBartosh** [comment]
@webhype Please make sure to create the .env files prior to running seed command. I ran into a similar issue, but worked after I have the .env files added.

**Comment by Mcastres** [comment]
I recently added the prerequisites in order to correctly start LaunchPad. Make sure to follow them :) 
Closing this then!
